#define PROJECTILEANIM_DEFAULT		0
#define PROJECTILEANIM_RICOCHET		1
#define PROJECTILEANIM_EXPLODE		2
#define PROJECTILEANIM_FROZEN		3

#define PROJECTILEDEATH_RANDOM		0
#define PROJECTILEDEATH_SHOTGUN		1
#define PROJECTILEDEATH_BURNING		2
