
// Default speed, meters per second
#define BULLET_DEFAULTVELOCITY					50

// Sniper is high so you always hit where aimed
#define BULLET_SNIPERVELOCITY					400

// Degrees, speed multiplier, minimum removal speed
#define BULLET_VISIBILITYSPEED					45

#define PROJECTILE_RICOCHET_MAXIMUMANGLE		15
#define PROJECTILE_RICOCHET_SPEEDMULTIPLIER		0.9
#define PROJECTILE_RICOCHET_MINIMUMSPEED		100	

#define PROJECTILE_CASE_RICOCHET_MAXIMUMANGLE		90
#define PROJECTILE_CASE_RICOCHET_SPEEDMULTIPLIER	0.3
#define PROJECTILE_CASE_RICOCHET_MINIMUMSPEED		3

#define PROJECTILE_CLIP_RICOCHET_MAXIMUMANGLE		90
#define PROJECTILE_CLIP_RICOCHET_SPEEDMULTIPLIER	0.3
#define PROJECTILE_CLIP_RICOCHET_MINIMUMSPEED		3

#define PROJECTILE_THROW_RICOCHET_MAXIMUMANGLE		90
#define PROJECTILE_THROW_RICOCHET_SPEEDMULTIPLIER	0.6
#define PROJECTILE_THROW_RICOCHET_MINIMUMSPEED		2

#define PROJECTILE_WEAPON_RICOCHET_MAXIMUMANGLE		90
#define PROJECTILE_WEAPON_RICOCHET_SPEEDMULTIPLIER	0.2
#define PROJECTILE_WEAPON_RICOCHET_MINIMUMSPEED		2
