// Crosshair attributes
#define	CROSSHAIR_CASTLENGTH			100

#define	CROSSHAIR_SIZEFRONTLIMIT		40.0
#define	CROSSHAIR_SIZEBACKLIMIT			40.0

//#define	CROSSHAIR_SPHERERADIUS			0.15
#define	CROSSHAIR_SPHERERADIUS			0.01
#define	CROSSHAIR_SNIPERSPHERERADIUS	0.01

// Beretta shared
#define	BERETTA_CLIPSIZE					18
#define	BERETTA_POCKETSIZE					162

// Beretta 
#define	BERETTA_SHOOTINGFREQUENCY			4
#define	BERETTA_MAXSHOOTINGFREQUENCY		4.001
#define	BERETTA_SLOWMOTIONMULTIPLIER		0.25
#define	BERETTA_BULLETDAMAGE				5
#define	BERETTA_BULLETSPREAD				100

#define	BERETTADUAL_SHOOTINGFREQUENCY		4
#define	BERETTADUAL_MAXSHOOTINGFREQUENCY	4.001
#define	BERETTADUAL_SLOWMOTIONMULTIPLIER	0.25
#define	BERETTADUAL_BULLETDAMAGE			5
#define	BERETTADUAL_BULLETSPREAD			200

// Desert Eagle
#define	DESERTEAGLE_SHOOTINGFREQUENCY		3
#define	DESERTEAGLE_MAXSHOOTINGFREQUENCY	3.001
#define	DESERTEAGLE_SLOWMOTIONMULTIPLIER	0.25
#define	DESERTEAGLE_BULLETDAMAGE			10
#define	DESERTEAGLE_BULLETSPREAD			50
#define	DESERTEAGLE_CLIPSIZE				12
#define	DESERTEAGLE_POCKETSIZE				48

// Shotgun shared, generic is the single straight flying bullet, pocketsize is for SawedShotgun and PumpShotgun
#define	SHOTGUN_GENERIC_BULLETDAMAGE		5
#define	SHOTGUN_GENERIC_BULLETSPREAD		20
#define	SHOTGUN_POCKETSIZE					80

#define	SAWEDSHOTGUN_SHOOTINGFREQUENCY		2
#define	SAWEDSHOTGUN_MAXSHOOTINGFREQUENCY	2.001
#define	SAWEDSHOTGUN_SLOWMOTIONMULTIPLIER	0.25
#define	SAWEDSHOTGUN_BULLETDAMAGE			5
#define	SAWEDSHOTGUN_BULLETSPREAD			400
#define	SAWEDSHOTGUN_CLIPSIZE				2

#define	PUMPSHOTGUN_SHOOTINGFREQUENCY		1
#define	PUMPSHOTGUN_MAXSHOOTINGFREQUENCY	1.001
#define	PUMPSHOTGUN_SLOWMOTIONMULTIPLIER	0.2
#define	PUMPSHOTGUN_BULLETDAMAGE			5
#define	PUMPSHOTGUN_BULLETSPREAD			150
#define	PUMPSHOTGUN_CLIPSIZE				7

#define	JACKHAMMER_SHOOTINGFREQUENCY		3
#define	JACKHAMMER_MAXSHOOTINGFREQUENCY		3.001
#define	JACKHAMMER_BULLETDAMAGE				5
#define	JACKHAMMER_BULLETSPREAD				300
#define	JACKHAMMER_CLIPSIZE					12
#define	JACKHAMMER_POCKETSIZE				168

// Machine guns
#define	INGRAM_CLIPSIZE						50
#define	INGRAM_POCKETSIZE					300

#define	INGRAM_SHOOTINGFREQUENCY			8
#define	INGRAM_MAXSHOOTINGFREQUENCY			8.001
#define	INGRAM_SLOWMOTIONMULTIPLIER			0.0
#define	INGRAM_BULLETDAMAGE					5
#define	INGRAM_BULLETSPREAD					300
#define	INGRAMDUAL_SHOOTINGFREQUENCY		8
#define	INGRAMDUAL_MAXSHOOTINGFREQUENCY		8.001
#define	INGRAMDUAL_SLOWMOTIONMULTIPLIER		0.0
#define	INGRAMDUAL_BULLETDAMAGE				5
#define	INGRAMDUAL_BULLETSPREAD				400

#define	MP5_SHOOTINGFREQUENCY				6
#define	MP5_MAXSHOOTINGFREQUENCY			6.001
#define	MP5_BULLETDAMAGE					10
#define	MP5_BULLETSPREAD					25
#define	MP5_CLIPSIZE						30
#define	MP5_POCKETSIZE						150

// Sniper
#define	SNIPER_SHOOTINGFREQUENCY			1
#define	SNIPER_MAXSHOOTINGFREQUENCY			1.001
#define	SNIPER_BULLETDAMAGE					70
#define	SNIPER_BULLETSPREAD					10
#define	SNIPER_CLIPSIZE						5
#define	SNIPER_POCKETSIZE					20

// Throwable / slow projectile weapons

#define	MOLOTOV_SHOOTINGFREQUENCY			1
#define	MOLOTOV_MAXSHOOTINGFREQUENCY		1.001
#define	MOLOTOV_CLIPSIZE					1
#define	MOLOTOV_POCKETSIZE					10

#define	GRENADE_SHOOTINGFREQUENCY			1
#define	GRENADE_MAXSHOOTINGFREQUENCY		1.001
#define	GRENADE_CLIPSIZE					1
#define	GRENADE_POCKETSIZE					10

#define	M79_SHOOTINGFREQUENCY				1
#define	M79_MAXSHOOTINGFREQUENCY			1.001
#define	M79_CLIPSIZE						1
#define	M79_POCKETSIZE						10
