#define GCID_UNASSIGNED						"<не определено>"
#define GCID_SEPARATOR						" или "
#define GCID_RESUMEGAME						"Вернуться в Игру"
#define GCID_RESUMEGAME_TIP					"Продолжить последнюю игру, в которую вы играли"
#define GCID_NEWGAME						"Новая Игра"
#define GCID_NEWGAME_TIP					"Запустить новую игру с начала"
#define GCID_SELECTLEVEL					"ВЫБЕРИТЕ УРОВЕНЬ ИГРЫ"
#define GCID_NORMAL							"Беглец"
#define GCID_NORMAL_TIP						"Игра - более тяжелые для прохождения уровни и Минута в Нью-Йорке станут доступными, когда вы завершите Режим Беглеца"
#define GCID_NIGHTMARE						"Сварен Вкрутую"
#define GCID_NIGHTMARE_TIP					"Идите и столкнитесь со следующим вызовом - Завершите этот уровень, чтобы перейти к Мертвец Прибывает"
#define GCID_HELL							"Мертвец Прибывает"
#define GCID_HELL_TIP						"Конечная Проверка"
#define GCID_TIMEDMODE						"Минута в Нью-Йорке"
#define GCID_TIMEDMODE_TIP					"Ограничение состоит в том, что у вас ограничено время на зачистку каждого уровня"
#define GCID_STARTTUTORIAL					"Обучение"
#define GCID_STARTTUTORIAL_TIP				"Загрузите обучающий уровень, чтобы познакомиться с основными механизмами игры"
#define GCID_LOAD							"Загрузка"
#define GCID_LOAD_TIP						"Показать список ранее сохраненных игр"
#define GCID_LOADGAME						"ЗАГРУЗКА ИГРЫ"
#define GCID_EMPTY_LOAD						"<пусто>"
#define GCID_EMPTY_LOAD_TIP					"Загрузить эту сохраненную игру"
#define GCID_SAVE							"Запись"
#define GCID_SAVE_TIP						"Показать список доступных для записи слотов"
#define GCID_SAVEGAME						"ЗАПИСЬ ИГРЫ"
#define GCID_EMPTY_SAVE						"<пусто>"
#define GCID_EMPTY_SAVE_TIP					"Сохранить здесь вашу текущую игру"
#define GCID_OPTIONS						"Опции"
#define GCID_OPTIONS_TIP					"Изменить или просмотреть управление и общие настройки, опции звука и видео"
#define GCID_OPTIONSU						"ОПЦИИ"
#define	GCID_CONTROLS						"Управление"
#define GCID_CONTROLS_TIP					"Изменить или просмотреть управление движением, боем и мышью"
#define GCID_CONTROLSU						"УПРАВЛЕНИЕ"
#define GCID_MOVEMENT						"Движение"
#define GCID_MOVEMENT_TIP					"Изменить или просмотреть общее управление движением"
#define GCID_CHANGEMOVEMENT					"КЛАВИШИ ДВИЖЕНИЯ"
#define GCID_FORWARD						"Вперед -"
#define GCID_FORWARD_TIP					"Нажмите Удалить, чтобы очистить / Выбрать, чтобы изменить клавишу или кнопку Движения вперед"
#define GCID_FORWARD_CHANGE_TIP				"Нажмите новую основную или вторичную клавишу или кнопку Движения вперед / ESC для отмены"
#define GCID_BACKWARD						"Назад -"
#define GCID_BACKWARD_TIP					"Нажмите Удалить, чтобы очистить / Выбрать, чтобы изменить клавишу или кнопку Движения назад"
#define GCID_BACKWARD_CHANGE_TIP			"Нажмите новую основную или вторичную клавишу или кнопку Движения назад / ESC для отмены"
#define GCID_STRAFELEFT						"Шаг Влево -"
#define GCID_STRAFELEFT_TIP					"Нажмите Удалить, чтобы очистить / Выбрать, чтобы изменить клавишу или кнопку Движения шага влево"
#define GCID_STRAFELEFT_CHANGE_TIP			"Нажмите новую основную или вторичную клавишу или кнопку Движения шага влево / ESC для отмены"
#define GCID_STRAFERIGHT					"Шаг Вправо -"
#define GCID_STRAFERIGHT_TIP				"Нажмите Удалить, чтобы очистить / Выбрать, чтобы изменить клавишу или кнопку Движения шага вправо"
#define GCID_STRAFERIGHT_CHANGE_TIP			"Нажмите новую основную или вторичную клавишу или кнопку Движения шага вправо / ESC для отмены"
#define GCID_CROUCH							"Присесть -"
#define GCID_CROUCH_TIP						"Нажмите Удалить, чтобы очистить / Выбрать, чтобы изменить клавишу или кнопку Приседания"
#define GCID_CROUCH_CHANGE_TIP				"Нажмите новую основную или вторичную клавишу или кнопку Приседания / ESC для отмены"
#define GCID_JUMP							"Прыжок -"
#define GCID_JUMP_TIP						"Нажмите Удалить, чтобы очистить / Выбрать, чтобы изменить клавишу или кнопку Прыжка"
#define GCID_JUMP_CHANGE_TIP				"Нажмите новую основную или вторичную клавишу или кнопку Прыжка / ESC для отмены"
#define GCID_ACTIVATE						"Использование / Прицел -"
#define GCID_ACTIVATE_TIP					"Нажмите Удалить, чтобы очистить / Выбрать, чтобы изменить клавишу или кнопку Использования / Снайперского Прицела"
#define GCID_ACTIVATE_CHANGE_TIP			"Нажмите новую основную или вторичную клавишу или кнопку Использования / Снайперского Прицела / ESC для отмены"
#define GCID_USEPAINKILLER					"Использование Болеутоляющего -"
#define GCID_USEPAINKILLER_TIP				"Нажмите Удалить, чтобы очистить / Выбрать, чтобы изменить клавишу или кнопку Использования Болеутоляющего"
#define GCID_USEPAINKILLER_CHANGE_TIP		"Нажмите новую основную или вторичную клавишу или кнопку Использования Болеутоляющего / ESC для отмены"
#define GCID_BULLETTIME						"Медленный кувырок -"
#define GCID_BULLETTIME_TIP					"Нажмите Удалить, чтобы очистить / Выбрать, чтобы изменить клавишу или кнопку Комбо Темпа Пуль"
#define GCID_BULLETTIME_CHANGE_TIP			"Нажмите новую основную или вторичную клавишу или кнопку Комбо Темпа Пуль / ESC для отмены"
#define GCID_SLOWMOTION						"Только замедление -"
#define GCID_SLOWMOTION_TIP					"Нажмите Удалить, чтобы очистить / Выбрать, чтобы изменить клавишу или кнопку Только Темпа Пуль (без Уклонения от пуль)"
#define GCID_SLOWMOTION_CHANGE_TIP			"Нажмите новую основную или вторичную клавишу или кнопку Только Темпа Пуль (без Уклонения от пуль) / ESC для отмены"
#define GCID_DODGEMODIFIER					"Только кувырок -"
#define GCID_DODGEMODIFIER_TIP				"Нажмите Удалить, чтобы очистить / Выбрать, чтобы изменить клавишу или кнопку Только Уклонения от Пуль "
#define GCID_DODGEMODIFIER_CHANGE_TIP		"Нажмите новую основную или вторичную клавишу или кнопку Только Уклонения от Пуль /ESC для отмены"
#define GCID_PAUSEGAME						"Пауза в Игре -"
#define GCID_PAUSEGAME_TIP					"Нажмите Удалить, чтобы очистить / Выбрать, чтобы изменить клавишу или кнопку Паузы в Игре"
#define GCID_PAUSEGAME_CHANGE_TIP			"Нажмите новую основную или вторичную клавишу или кнопку Паузы в Игре / ESC для отмены"
#define GCID_COMBAT							"Бой"
#define GCID_COMBAT_TIP						"Изменить или просмотреть управление в бою"
#define GCID_CHANGECOMBAT					"БОЕВЫЕ КЛАВИШИ"
#define GCID_SHOOT							"Выстрел -"
#define GCID_SHOOT_TIP						"Нажмите Удалить, чтобы очистить / Выбрать, чтобы изменить клавишу или кнопку Выстрела"
#define GCID_SHOOT_CHANGE_TIP				"Нажмите новую основную или вторичную клавишу или кнопку Выстрела / ESC для отмены"
#define GCID_RELOAD							"Перезарядка -"
#define GCID_RELOAD_TIP						"Нажмите Удалить, чтобы очистить / Выбрать, чтобы изменить клавишу или кнопку Перезарядки"
#define GCID_RELOAD_CHANGE_TIP				"Нажмите новую основную или вторичную клавишу или кнопку Перезарядки / ESC для отмены"
#define GCID_NEXTWEAPON						"Следующее Оружие -"
#define GCID_NEXTWEAPON_TIP					"Нажмите Удалить, чтобы очистить / Выбрать, чтобы изменить клавишу, кнопку или назначить колесико мыши для Следующего Оружия"
#define GCID_NEXTWEAPON_CHANGE_TIP			"Нажмите новую основную или вторичную клавишу, или кнопку, или колесико мыши для Следующего Оружия / ESC для отмены"
#define GCID_PREVIOUSWEAPON					"Предыдущее Оружие -"
#define GCID_PREVIOUSWEAPON_TIP				"Нажмите Удалить, чтобы очистить / Выбрать, чтобы изменить клавишу, кнопку или назначить колесико мыши для Предыдущего Оружия"
#define GCID_PREVIOUSWEAPON_CHANGE_TIP		"Нажмите новую основную или вторичную клавишу, или кнопку, или колесико мыши для Предыдущего Оружия / ESC для отмены"
#define GCID_SELECTBESTWEAPON				"Выбор Лучшего Оружия -"
#define GCID_SELECTBESTWEAPON_TIP			"Нажмите Удалить, чтобы очистить / Выбрать, чтобы изменить клавишу или кнопку Выбора Лучшего Оружия"
#define GCID_SELECTBESTWEAPON_CHANGE_TIP	"Нажмите новую основную или вторичную клавишу или кнопку Выбора Лучшего Оружия / ESC для отмены"
#define GCID_MELEE							"Оружие Ближнего Боя -"
#define GCID_MELEE_TIP						"Нажмите Удалить, чтобы очистить / Выбрать, чтобы изменить клавишу или кнопку выбора Оружия Ближнего Боя"
#define GCID_MELEE_CHANGE_TIP				"Нажмите новую основную или вторичную клавишу или кнопку выбора Оружия Ближнего Боя / ESC для отмены"
#define GCID_HANDGUNS						"Пистолеты -"
#define GCID_HANDGUNS_TIP					"Нажмите Удалить, чтобы очистить / Выбрать, чтобы изменить клавишу или кнопку выбора Пистолетов"
#define GCID_HANDGUNS_CHANGE_TIP			"Нажмите новую основную или вторичную клавишу или кнопку выбора Пистолетов / ESC для отмены"
#define GCID_SHOTGUNS						"Дробовики -"
#define GCID_SHOTGUNS_TIP					"Нажмите Удалить, чтобы очистить / Выбрать, чтобы изменить клавишу или кнопку выбора Дробовиков"
#define GCID_SHOTGUNS_CHANGE_TIP			"Нажмите новую основную или вторичную клавишу или кнопку выбора Дробовиков / ESC для отмены"
#define GCID_MACHINEGUNS					"Автоматическое Оружие -"
#define GCID_MACHINEGUNS_TIP				"Нажмите Удалить, чтобы очистить / Выбрать, чтобы изменить клавишу или кнопку выбора Автоматического Оружия"
#define GCID_MACHINEGUNS_CHANGE_TIP			"Нажмите новую основную или вторичную клавишу или кнопку выбора Автоматического Оружия / ESC для отмены"
#define GCID_THROWABLE						"Метательное Оружие -"
#define GCID_THROWABLE_TIP					"Нажмите Удалить, чтобы очистить / Выбрать, чтобы изменить клавишу или кнопку выбора Метательного Оружия"
#define GCID_THROWABLE_CHANGE_TIP			"Нажмите новую основную или вторичную клавишу или кнопку выбора Метательного Оружия / ESC для отмены"
#define GCID_SNIPER							"Снайперская Винтовка -"
#define GCID_SNIPER_TIP						"Нажмите Удалить, чтобы очистить / Выбрать, чтобы изменить клавишу или кнопку выбора Снайперской Винтовки"
#define GCID_SNIPER_CHANGE_TIP				"Нажмите новую основную или вторичную клавишу или кнопку выбора Снайперской Винтовки / ESC для отмены"
#define GCID_MOUSESETTINGS					"Настройки Мыши"
#define GCID_MOUSESETTINGS_TIP				"Изменить или просмотреть настройки мыши"
#define GCID_MOUSESETTINGSU					"НАСТРОЙКИ МЫШИ"
#define GCID_AIMINGHSPEED					"Горизонтальное Прицеливание"
#define GCID_AIMINGHSPEED_TIP				"Используйте клавиши курсора или мышь, чтобы изменить скорость горизонтального прицеливания"
#define GCID_AIMINGVSPEED					"Вертикальное Прицеливание"
#define GCID_AIMINGVSPEED_TIP				"Используйте клавиши курсора или мышь, чтобы изменить скорость вертикального прицеливания"
#define GCID_INVERTMOUSE					"Инвертация Мыши"
#define GCID_INVERTMOUSE_TIP				"Инвертация движения вертикального прицеливания для мыши"
#define GCID_INVERTMOUSEWHEEL				"Инвертация Колесика Мыши"
#define GCID_INVERTMOUSEWHEEL_TIP			"Инвертация переключения оружия колесиком мыши"
#define GCID_RESTOREDEFAULTS				"Восстановить Начальные"
#define GCID_RESTOREDEFAULTS_TIP			"Восстановление настроек управления, заданных по умолчанию"
#define GCID_GENERIC						"Игра"
#define GCID_GENERIC_TIP					"Изменить или просмотреть общие игровые опции"
#define GCID_GENERICU						"ИГРА"
#define GCID_SHOWCROSSHAIR					"Изображение Прицела"
#define GCID_SHOWCROSSHAIR_TIP				"Переключение изображения прицела на экране"
#define GCID_ENABLEAUTOAIM					"Включение Автоприцеливания"
#define GCID_ENABLEAUTOAIM_TIP				"Переключение Автоприцеливания"
#define GCID_ENABLETIPS						"Включение Игровых Подсказок"
#define GCID_ENABLETIPS_TIP					"Переключение помощи Игровых Подсказок"
#define GCID_AUTOWEAPONCHANGE				"Автосмена Оружия"
#define GCID_AUTOWEAPONCHANGE_TIP			"Переключение Автоматического Выбора Лучшего Оружия при нахождении нового оружия"
#define GCID_BULLETTIMEAID					"Включение Помощи Темпа Пуль"
#define GCID_BULLETTIMEAID_TIP				"Максимально возможная экономия Темпа Пуль с помощью автоматического отключения Темпа Пуль в некоторых игровых ситуация"
#define GCID_READSTORY						"Чтение Историй - F1"
#define GCID_READSTORY_TIP					"Прочтение истории, до которой вы добрались - назначенная клавиша не может быть изменена"
#define GCID_SHOWOBJECTIVES					"Показ Целей - F2"
#define GCID_SHOWOBJECTIVES_TIP				"Показ целей уровня - назначенная клавиша не может быть изменена"
#define GCID_QUICKSAVE						"Быстрая Запись - F5"
#define GCID_QUICKSAVE_TIP					"Сохранение вашей текущей игры в слот быстрой записи - назначенная клавиша не может быть изменена"
#define GCID_QUICKLOAD						"Быстрая Загрузка - F9"
#define GCID_QUICKLOAD_TIP					"Загрузка самой последней сохраненной игры - назначенная клавиша не может быть изменена"
#define GCID_VIDEO							"Видео"
#define GCID_VIDEO_TIP						"Изменение или просмотр настроек видео"
#define GCID_VIDEOU							"ВИДЕО"
#define GCID_TEXTUREMIPMAP					"Резкость Текстур  "
#define GCID_TEXTUREMIPMAP_TIP				"Используйте клавиши курсора или мышь, чтобы подстроить резкость текстур"
#define GCID_GAMMACONTROL					"Яркость  "
#define GCID_GAMMACONTROL_TIP				"Используйте клавиши курсора или мышь, чтобы подстроить яркость"
#define GCID_SOUND							"Звук"
#define GCID_SOUND_TIP						"Изменение или просмотр настроек звука"
#define GCID_SOUNDU							"ЗВУК"
#define GCID_MUSICVOLUME					"Громкость Музыки"
#define GCID_MUSICVOLUME_TIP				"Используйте клавиши курсора или мышь, чтобы подстроить громкость музыки"
#define GCID_EFFECTSVOLUME					"Громкость Звуков"
#define GCID_EFFECTSVOLUME_TIP				"Используйте клавиши курсора или мышь, чтобы подстроить громкость звуков"
#define GCID_QUIT							"Выход"
#define GCID_QUIT_TIP						"Выход из игры Макс Пейн"
#define GCID_CREDITS						"Создатели"
#define GCID_CREDITS_TIP					"Просмотр Создателей"


#define	GCID_QUITJOKE01						"                                               Снаружи в ночи освободились мои враги."
#define	GCID_QUITJOKE02						"                                               Поезд становился все холоднее."
#define	GCID_QUITJOKE03						"                                               Ничто не было решено."
#define	GCID_QUITJOKE04						"                                               Никто не был отомщен."
#define	GCID_QUITJOKE05						"                                               Ответы, которые я хотел получить, были далеко впереди."
#define	GCID_QUITJOKE06						"                                               Призраки моих любимых были лишены покоя."
#define	GCID_QUITJOKE07						"                                               Ночь в Городе Нью-Йорке только начиналась."
#define	GCID_QUITJOKE08						"                                               Я не нашел никаких ответов на свои вопросы."
#define	GCID_QUITJOKE09						"                                               Ничего не оставалось, кроме как закрыть дело Валькирии."
#define	GCID_QUITJOKE10						"                                               Месть была тенью в моем сердце."
#define	GCID_QUITJOKE11						"                                               Зимняя ночь бесконечно тянулась передо мной."
#define	GCID_QUITJOKE12						"                                               Сердце колотилось у меня в горле."
#define	GCID_QUITJOKE13						"                                               Мое путешествие в ночь было далеко от завершения."
#define	GCID_QUITJOKE14						"                                               Шепот мертвых не давал мне заснуть."
#define	GCID_QUITJOKE15						"                                               Мой пистолет жадно зашевелился под моим пиджаком."
#define	GCID_QUITJOKE16						"                                               Город, который никогда не спит, пялился мне в глаза."
#define	GCID_QUITJOKE17						"                                               Снаружи в ночи V продолжал распространяться как рак."
#define	GCID_QUITJOKE18						"                                               В ночи постоянно раздавался вой сирен."
#define	GCID_QUITJOKE19						"                                               Город Нью-Йорк смотрел на меня глазами охотника."
#define	GCID_QUITJOKE20						"                                               Смерть бродит по улицам города сегодня вечером."
#define	GCID_QUITJOKE21						"                                               Когда я закрывал свои глаза, я мог их видеть, мертвых."
#define	GCID_QUITJOKE22						"                                               Все причины были таинственными, прячущимися во тьме."
#define	GCID_QUITJOKE23						"                                               Я не сдержал обещания, данного своим любимым."
#define	GCID_QUITJOKE24						"                                               Дело V было столь же сложным, как и карта города."
#define	GCID_QUITJOKE25						"                                               Месть была болью за моими глазами."

#define GCID_QUIT_YES						"                                               Но я слишком устал, чтобы продолжать."
#define GCID_QUIT_NO						"                                               Я не мог остановиться. Я должен был спешить."

#define GCID_AREYOUSURE						"Вы уверены?"
#define GCID_YES							"Да"
#define GCID_YES_TIP						"Принять изменения"
#define GCID_NO								"Нет"
#define GCID_NO_TIP							"Отменить изменения"
#define GCID_BACK							"Назад"
#define GCID_BACK_TIP						"Назад на предыдущую страницу"
#define GCID_QUIT_YES_TIP					"Выход из текущей игры и возвращение на рабочий стол"
#define GCID_QUIT_NO_TIP					"Вернуться в главное меню"

#define SGID_LOADHUDTEXT					"Игра загружена"
#define SGID_SAVEHUDTEXT					"Игра сохранена"
#define SGID_SAVELIMITEDHUDTEXT				"Игра сохранена - %i мест для записи осталось"
#define SGID_UNABLETOSAVEHUDTEXT			"! Не осталось места для записи"
#define SGID_SAVEGAMENOTFOUNDHUDTEXT		"Нет игры для загрузки"
#define SGID_CANNOTSAVEHUDTEXT				"Невозможно записать игру в данный момент"
#define SGID_SAVINGFAILEDHUDTEXT			"Невозможно записать файл сохранения игры - игра не сохранена"
#define	SGID_OUTOFTIME						"Ваше время истекло!"

#define LNID_TUTORIAL 						"Обучение"
#define LNID_PART1_PROLOGUE					"Часть I, Пролог"
#define LNID_PART1_CHAPTER1					"Часть I, Глава Один"
#define LNID_PART1_CHAPTER2					"Часть I, Глава Два"	
#define LNID_PART1_CHAPTER3					"Часть I, Глава Три"
#define LNID_PART1_CHAPTER4					"Часть I, Глава Четыре"
#define LNID_PART1_CHAPTER5					"Часть I, Глава Пять"
#define LNID_PART1_CHAPTER6					"Часть I, Глава Шесть"
#define LNID_PART1_CHAPTER7					"Часть I, Глава Семь"
#define LNID_PART1_CHAPTER8					"Часть I, Глава Восемь"
#define LNID_PART1_CHAPTER9					"Часть I, Глава Девять"
#define LNID_PART2_PROLOGUE					"Часть II, Пролог"
#define LNID_PART2_CHAPTER1					"Часть II, Глава Один"
#define LNID_PART2_CHAPTER2					"Часть II, Глава Два"	
#define LNID_PART2_CHAPTER3					"Часть II, Глава Три"
#define LNID_PART2_CHAPTER4					"Часть II, Глава Четыре"
#define LNID_PART2_CHAPTER5					"Часть II, Глава Пять"
#define LNID_PART2_CHAPTER6					"Часть II, Глава Шесть"
#define LNID_PART3_PROLOGUE					"Часть III, Пролог"
#define LNID_PART3_CHAPTER1					"Часть III, Глава Один"
#define LNID_PART3_CHAPTER2					"Часть III, Глава Два"	
#define LNID_PART3_CHAPTER3					"Часть III, Глава Три"
#define LNID_PART3_CHAPTER4					"Часть III, Глава Четыре"
#define LNID_PART3_CHAPTER5					"Часть III, Глава Пять"
#define LNID_PART3_CHAPTER6					"Часть III, Глава Шесть"
#define LNID_PART3_CHAPTER7					"Часть III, Глава Семь"
#define LNID_PART3_CHAPTER8					"Часть III, Глава Восемь"

#define LNID_END_COMBAT						"Секретный Финал"

// graphic novel mode pause text is here since it's not a hud print
#define	GNID_TIP_PREVIOUS_CHAPTER			"Предыдущая Глава"
#define	GNID_TIP_PREVIOUS_PAGE				"Предыдущая Страница"
#define	GNID_TIP_PLAY						"Показать"
#define	GNID_TIP_STOP						"Стоп"
#define	GNID_TIP_NEXT_PAGE					"Следующая Страница"
#define	GNID_TIP_NEXT_CHAPTER				"Следующая Глава"
#define	GNID_TIP_QUIT						"Назад к Игре"

#define GNID_PAUSE							"Пауза";