#define	WEAPONANIM_NOTAVAIL		0x7FFFFFFF

#define WEAPONANIM_DEFAULT			0
#define WEAPONANIM_SHOOT			1
#define WEAPONANIM_SHOOT_NOCASE		2
#define WEAPONANIM_SHOOT_NOEFFECTS	3
#define WEAPONANIM_SHOOTEMPTY		4
#define WEAPONANIM_RELOAD			5
#define WEAPONANIM_DROPONDEATH		6
